OPENAI:
  api_key: "sk-*****"
  base_url: "https://api.deepseek.com"
  model: "deepseek-chat"
  max_concurrency: 10

VLM:
  api_key: "sk-*****"
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  model: "qwen2.5-vl-72b-instruct"
  max_concurrency: 10
  
OCR:
  enabled: true

POPPLER:
  path: "D:/Personal_Project/docling/poppler/Library/bin"
