OPENAI:
  api_key: "sk-******"
  base_url: "https://api.deepseek.com"
  model: "deepseek-chat"

VLM:
  api_key: "sk-******"
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  model: "qwen2.5-vl-72b-instruct"

OCR:
  enabled: true
